version: "1"
services:
  ### Mysql container
  mysql:
    container_name: mysql-server
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rute
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes